version: '3.0'

services:
  python:
    container_name: python
    build: python
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    restart: always
    networks:
      - python-network

  db:
    image: mysql:8.0.26
    container_name: db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - python-network

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - "6080:8080"
    networks:
      - python-network

networks:
  python-network:
    driver: bridge